{
 "PRed":[
  {
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"2.0.4"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/205754474.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Compiler",
    "migrator_version":0
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/210711637.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"3.0.0"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/231700023.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"CompilerRebuild",
    "migrator_version":1,
    "name":"Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/261551481.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"3.2.0"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/294519637.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"3.3.0"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/298360007.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"RBaseRebuild",
    "migrator_version":0,
    "name":"r-base-3.6.1"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad":{
  "exception":"<class 'requests.exceptions.ReadTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
  "traceback":[
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 421, in _make_request",
   "    six.raise_from(e, None)",
   "  File \"<string>\", line 3, in raise_from",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 416, in _make_request",
   "    httplib_response = conn.getresponse()",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/http/client.py\", line 1321, in getresponse",
   "    response.begin()",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/http/client.py\", line 296, in begin",
   "    version, status, reason = self._read_status()",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/http/client.py\", line 257, in _read_status",
   "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/socket.py\", line 589, in readinto",
   "    return self._sock.recv_into(b)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py\", line 326, in recv_into",
   "    raise timeout(\"The read operation timed out\")",
   "socket.timeout: The read operation timed out",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send",
   "    timeout=timeout",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 720, in urlopen",
   "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/util/retry.py\", line 400, in increment",
   "    raise six.reraise(type(error), error, _stacktrace)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/packages/six.py\", line 735, in reraise",
   "    raise value",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 672, in urlopen",
   "    chunked=chunked,",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 423, in _make_request",
   "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 331, in _raise_timeout",
   "    self, url, \"Read timed out. (read timeout=%s)\" % timeout_value",
   "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/models.py\", line 196, in _request",
   "    return request_method(*args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/sessions.py\", line 581, in post",
   "    return self.request('POST', url, data=data, json=json, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/session.py\", line 169, in request",
   "    response = super(GitHubSession, self).request(*args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/sessions.py\", line 533, in request",
   "    resp = self.send(prep, **send_kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/sessions.py\", line 646, in send",
   "    r = adapter.send(request, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/adapters.py\", line 529, in send",
   "    raise ReadTimeout(e, request=request)",
   "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh\", line 745, in main",
   "    hash_type=attrs.get('hash_type', 'sha256'))",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh\", line 130, in run",
   "    migrator.remote_branch())",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/git_utils.xsh\", line 240, in push_repo",
   "    pr = repo.create_pull(title, 'master', head, body=body)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/decorators.py\", line 31, in auth_wrapper",
   "    return func(self, *args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/repos/repo.py\", line 1117, in create_pull",
   "    return self._create_pull(data)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/repos/repo.py\", line 120, in _create_pull",
   "    json = self._json(self._post(url, data=data), 201)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/models.py\", line 221, in _post",
   "    return self._request(\"post\", url, data, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/models.py\", line 201, in _request",
   "    raise exceptions.ConnectionError(exc)",
   "github3.exceptions.ConnectionError: <class 'requests.exceptions.ReadTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   ""
  ]
 },
 "conda-forge.yml":{
  "compiler_stack":"comp7",
  "max_py_ver":"37",
  "max_r_ver":"35",
  "provider":{
   "win":"azure"
  }
 },
 "feedstock_name":"r-callr",
 "hash_type":"sha256",
 "meta_yaml":{
  "about":{
   "home":"https://github.com/r-lib/callr#readme",
   "license":"MIT",
   "license_family":"MIT",
   "license_file":[
    "/lib/R/share/licenses/MIT",
    "LICENSE",
    "/lib/R/share/licenses/MIT",
    "LICENSE",
    "/lib/R/share/licenses/MIT",
    "LICENSE"
   ],
   "summary":"It is sometimes useful to perform a computation in a separate R process, without affecting the current R process at all. This packages does exactly that."
  },
  "build":{
   "merge_build_host":true,
   "noarch":"generic",
   "number":"0",
   "rpaths":[
    "lib/R/lib/",
    "lib/",
    "lib/R/lib/",
    "lib/",
    "lib/R/lib/",
    "lib/"
   ]
  },
  "extra":{
   "recipe-maintainers":[
    "conda-forge/r",
    "conda-forge/r",
    "conda-forge/r"
   ]
  },
  "package":{
   "name":"r-callr",
   "version":"3.3.2"
  },
  "requirements":{
   "build":null,
   "host":[
    "r-base",
    "r-r6",
    "r-processx >=3.4.0",
    "r-base",
    "r-r6",
    "r-processx >=3.4.0",
    "r-base",
    "r-r6",
    "r-processx >=3.4.0"
   ],
   "run":[
    "r-base",
    "r-r6",
    "r-processx >=3.4.0",
    "r-base",
    "r-r6",
    "r-processx >=3.4.0",
    "r-base",
    "r-r6",
    "r-processx >=3.4.0"
   ]
  },
  "source":{
   "sha256":"d0e6066d111a8642aa1412efd0377beaa2ee3c5d017bc07dc3caaf67e5c7ab89",
   "url":[
    "https://cran.r-project.org/src/contrib/callr_3.3.2.tar.gz",
    "https://cran.r-project.org/src/contrib/Archive/callr/callr_3.3.2.tar.gz",
    "https://cran.r-project.org/src/contrib/callr_3.3.2.tar.gz",
    "https://cran.r-project.org/src/contrib/Archive/callr/callr_3.3.2.tar.gz",
    "https://cran.r-project.org/src/contrib/callr_3.3.2.tar.gz",
    "https://cran.r-project.org/src/contrib/Archive/callr/callr_3.3.2.tar.gz"
   ]
  },
  "test":{
   "commands":[
    "\"%R%\" -e \"library('callr')\"",
    "$R -e \"library('callr')\"",
    "$R -e \"library('callr')\""
   ]
  }
 },
 "name":"r-callr",
 "new_version":"3.4.0",
 "pinning_version":"2019.07.15",
 "raw_meta_yaml":"{% set version = '3.3.2' %}\n{% set posix = 'm2-' if win else '' %}\n{% set native = 'm2w64-' if win else '' %}\n\npackage:\n  name: r-callr\n  version: {{ version|replace(\"-\", \"_\") }}\n\nsource:\n  url:\n    - {{ cran_mirror }}/src/contrib/callr_{{ version }}.tar.gz\n    - {{ cran_mirror }}/src/contrib/Archive/callr/callr_{{ version }}.tar.gz\n  sha256: d0e6066d111a8642aa1412efd0377beaa2ee3c5d017bc07dc3caaf67e5c7ab89\n\nbuild:\n  merge_build_host: True  # [win]\n  number: 0\n  noarch: generic\n  rpaths:\n    - lib/R/lib/\n    - lib/\n\nrequirements:\n  build:\n    - {{posix}}zip               # [win]\n  host:\n    - r-base\n    - r-r6\n    - r-processx >=3.4.0\n  run:\n    - r-base\n    - r-r6\n    - r-processx >=3.4.0\n\ntest:\n  commands:\n    - $R -e \"library('callr')\"           # [not win]\n    - \"\\\"%R%\\\" -e \\\"library('callr')\\\"\"  # [win]\n\nabout:\n  home: https://github.com/r-lib/callr#readme\n  license: MIT\n  summary: It is sometimes useful to perform a computation in a separate R process, without affecting\n    the current R process at all. This packages does exactly that.\n  license_family: MIT\n  license_file:\n    - '{{ environ[\"PREFIX\"] }}/lib/R/share/licenses/MIT'\n    - LICENSE\n\nextra:\n  recipe-maintainers:\n    - conda-forge/r\n\n# Package: callr\n# Title: Call R from R\n# Version: 3.3.2\n# Authors@R: c( person(\"Gabor\", \"Csardi\", role = c(\"aut\", \"cre\", \"cph\"), email = \"csardi.gabor@gmail.com\", comment = c(ORCID = \"0000-0001-7098-9676\")), person(\"Winston\", \"Chang\", role = \"aut\"), person(\"RStudio\", role = c(\"cph\", \"fnd\")), person(\"Mango Solutions\", role  = c(\"cph\", \"fnd\")))\n# Description: It is sometimes useful to perform a computation in a separate R process, without affecting the current R process at all. This packages does exactly that.\n# License: MIT + file LICENSE\n# LazyData: true\n# URL: https://github.com/r-lib/callr#readme\n# BugReports: https://github.com/r-lib/callr/issues\n# RoxygenNote: 6.1.1\n# Imports: processx (>= 3.4.0), R6, utils\n# Suggests: cliapp, covr, crayon, fansi, knitr, pingr, ps, rmarkdown, rprojroot, spelling, testthat, tibble, withr\n# Encoding: UTF-8\n# VignetteBuilder: knitr\n# Language: en-US\n# NeedsCompilation: no\n# Packaged: 2019-09-22 09:12:55 UTC; gaborcsardi\n# Author: Gabor Csardi [aut, cre, cph] (<https://orcid.org/0000-0001-7098-9676>), Winston Chang [aut], RStudio [cph, fnd], Mango Solutions [cph, fnd]\n# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>\n# Repository: CRAN\n# Date/Publication: 2019-09-22 09:50:02 UTC\n",
 "req":{
  "__set__":true,
  "elements":[
   "r-base",
   "r-processx",
   "r-r6"
  ]
 },
 "smithy_version":"3.4.1",
 "url":[
  "https://cran.r-project.org/src/contrib/callr_3.3.1.tar.gz",
  "https://cran.r-project.org/src/contrib/Archive/callr/callr_3.3.1.tar.gz",
  "https://cran.r-project.org/src/contrib/callr_3.3.1.tar.gz",
  "https://cran.r-project.org/src/contrib/Archive/callr/callr_3.3.1.tar.gz",
  "https://cran.r-project.org/src/contrib/callr_3.3.1.tar.gz",
  "https://cran.r-project.org/src/contrib/Archive/callr/callr_3.3.1.tar.gz"
 ],
 "version":"3.3.2"
}